import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — MAMPF",
  description: "How MAMPF handles your data.",
};

export default function PrivacyPage() {
  return (
    <main className="h-screen overflow-y-auto bg-white text-[color:var(--color-foreground)]">
      <div className="mx-auto max-w-2xl px-6 py-12 pb-24">
        <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="mt-2 text-sm text-[color:var(--color-ff-muted)]">
          Last updated: 2026-04-24
        </p>

        <div className="prose mt-8 max-w-none text-[15px] leading-relaxed text-[color:var(--color-foreground)] [&_a]:text-[color:var(--color-ff-primary)] [&_a]:underline [&_h2]:mt-10 [&_h2]:text-xl [&_h2]:font-bold [&_h3]:mt-6 [&_h3]:text-base [&_h3]:font-semibold [&_p]:mt-3 [&_ul]:mt-3 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mt-1">
          <p>
            MAMPF (“we”, “us”) is a personal restaurant recommendation app for
            Hamburg, built by Jan Hoferichter. This policy explains what data
            we collect, why, and how to control it.
          </p>

          <h2>What we collect</h2>

          <h3>If you create an account</h3>
          <ul>
            <li>
              <strong>Email address</strong> — used to sign in and deliver
              account-related emails (e.g. confirmation, password reset).
              Stored by our auth provider Supabase.
            </li>
            <li>
              <strong>Display name</strong> (optional) — shown in your profile
              and used for personalized greetings. You can change or remove it
              anytime in “Edit Profile”.
            </li>
            <li>
              <strong>User ID</strong> — a random identifier generated by
              Supabase to associate your ratings with your account.
            </li>
            <li>
              <strong>Your restaurant ratings</strong> (scores 1–10) — tied to
              your account so you can see them across devices.
            </li>
            <li>
              <strong>Your favorites / “want to try” list</strong> — currently
              stored locally on your device only.
            </li>
          </ul>

          <h3>If you’re not signed in</h3>
          <ul>
            <li>
              <strong>Anonymous device ID</strong> — a random identifier stored
              locally so your ratings can be saved without an account. It is
              never combined with your name, email, or other personal data.
            </li>
            <li>
              <strong>Your restaurant ratings</strong> — tied to the anonymous
              device ID only.
            </li>
          </ul>

          <h3>Location</h3>
          <ul>
            <li>
              We request your location only <strong>while you’re using the
              app</strong>, and only if you grant permission.
            </li>
            <li>
              It is used <strong>client-side only</strong> to show your
              position on the map and calculate distance to restaurants.
            </li>
            <li>
              Your location is{" "}
              <strong>never transmitted to our servers or any third party</strong>.
            </li>
          </ul>

          <h2>What we don’t do</h2>
          <ul>
            <li>
              <strong>No tracking across apps or websites.</strong> No
              advertising SDKs, no fingerprinting.
            </li>
            <li>
              <strong>No analytics SDKs.</strong> We don’t know which screens
              you visit or how long you use the app.
            </li>
            <li>
              <strong>No selling or sharing of personal data</strong> with
              third parties for marketing.
            </li>
          </ul>

          <h2>Third-party services we use</h2>
          <ul>
            <li>
              <strong>Supabase</strong> (hosted in the EU) — PostgreSQL
              database + authentication. Stores your account, ratings, and
              favorites.{" "}
              <a href="https://supabase.com/privacy" target="_blank" rel="noreferrer">
                Privacy policy
              </a>
            </li>
            <li>
              <strong>Google Places API</strong> — used to fetch restaurant
              metadata (address, opening hours, public ratings). Restaurant
              data is requested by us on your behalf; Google does not receive
              your identity.{" "}
              <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">
                Privacy policy
              </a>
            </li>
            <li>
              <strong>Apple iCloud Keychain</strong> (optional) — used to save
              your login if you opt in via the iOS “Save Password” prompt.
            </li>
          </ul>

          <h2>Your rights and controls</h2>
          <p>You control your data at all times:</p>
          <ul>
            <li>
              <strong>Edit your profile</strong> — change your name or email
              anytime via Profile → tap your name.
            </li>
            <li>
              <strong>Delete your account</strong> — Profile → Settings →
              “Delete my account”. Permanently removes your account, all
              ratings, all favorites. Cannot be undone.
            </li>
            <li>
              <strong>Delete data without deleting the account</strong> —
              Profile → Settings → “Delete my data” while signed out (removes
              device-scoped anonymous ratings and resets the device ID).
            </li>
            <li>
              <strong>Export your data</strong> — email us and we’ll provide
              an export within 30 days.
            </li>
            <li>
              <strong>Revoke location access</strong> — iOS Settings → MAMPF →
              Location.
            </li>
          </ul>

          <h2>Data retention</h2>
          <ul>
            <li>
              <strong>Account data:</strong> retained until you delete your
              account.
            </li>
            <li>
              <strong>Anonymous ratings (device ID):</strong> retained until
              you tap “Delete my data” in Settings.
            </li>
            <li>
              <strong>Backups</strong> may retain copies for up to 30 days
              after deletion before being purged.
            </li>
          </ul>

          <h2>Children</h2>
          <p>
            MAMPF is not directed at children under 13. We do not knowingly
            collect data from children.
          </p>

          <h2>Changes to this policy</h2>
          <p>
            If we make material changes we’ll update the “Last updated” date
            above and notify signed-in users in-app.
          </p>

          <h2>Contact</h2>
          <p>
            Questions, data requests, or concerns:{" "}
            <a href="mailto:jan.hoferichter@apploft.de">
              jan.hoferichter@apploft.de
            </a>
          </p>
          <p>Data controller: Jan Hoferichter, Hamburg, Germany.</p>
        </div>
      </div>
    </main>
  );
}
